// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDpA6bzDv6udzeATTj80MWqEuay53mr5k',
    appId: '1:681469129711:web:c08690ecb074e43ffe3c1a',
    messagingSenderId: '681469129711',
    projectId: 'flutter-firebase-ca7d1',
    authDomain: 'flutter-firebase-ca7d1.firebaseapp.com',
    storageBucket: 'flutter-firebase-ca7d1.appspot.com',
    measurementId: 'G-1M671DNL5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGJD6eCfz83zxQcncsgDA9WUwPJhfbNbs',
    appId: '1:681469129711:android:17ea8782d0cef794fe3c1a',
    messagingSenderId: '681469129711',
    projectId: 'flutter-firebase-ca7d1',
    storageBucket: 'flutter-firebase-ca7d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZqEhI_hck4gqwquIUebvbsXpYiTtTDLo',
    appId: '1:681469129711:ios:51079c9b8a314726fe3c1a',
    messagingSenderId: '681469129711',
    projectId: 'flutter-firebase-ca7d1',
    storageBucket: 'flutter-firebase-ca7d1.appspot.com',
    iosClientId: '681469129711-vacb3kog53m9emh8nobul82dk2iiq52c.apps.googleusercontent.com',
    iosBundleId: 'com.example.allFirebase',
  );
}
